services:
  - type: web
    name: finance-agent
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install -e .
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false 